### ISSUE TITLE
CORS Error on SSR

### ISSUE THREAD

**Issue by figaro27** [uupd/LTH#12]
I have a Nuxt 3 SSR application hosted at [staging.eightpoint.ky](https://staging.eightpoint.ky/) which makes calls to an external API. The application behaves fine on initialization or on refresh, since all of the data is loaded server-side, but when I navigate to another page using NuxtLink, it sends a preflight request from the client and a CORS error occurs. To make things even more interesting, the error only occurs when on a network other than my internal office network, regardless of whether in a development or production environment. The proper CORS headers are present when the client request succeeds, so I am pretty sure it isn't the API CORS configuration which is causing the error.

**Comment by sol2dtdev** [comment]
well done
